### ISSUE TITLE
Shutdown Computer Using Voice

### ISSUE THREAD

**Issue by AmitGupta700** [prathimacode-hub/Awesome_Python_Scripts#130]
Title: Shutdown Computer Using Voice 

About: Using your voice command, will shut down your PC.

Name: Amit Gupta

Label: Feature Request

Defines you:
- [x] LGM-SOC'21 Participant

Describe the Approach:
I'll be using **OS**, **pyttsx3**, **speech_recongnition** for making it more functional in this script.

**Comment by prathimacode-hub** [comment]
Kindly, do the changes needed for your PR before you take up an another issue. Once you finish that, I can assign this issue to you. @AmitGupta700

**Comment by Sejal2801** [comment]
Please assign it to me

**Comment by prathimacode-hub** [comment]
Create a new issue using the template to get issue assigned it to you.  @Sejal2801

**Comment by Sejal2801** [comment]
Okay thankyou

**Comment by AmitGupta700** [comment]
> n assign this issue to you.

Mam what issue? I have submitted the last project

**Comment by Debashish-hub** [comment]
What you have submitted @AmitGupta700

**Comment by AmitGupta700** [comment]
> Kindly, do the changes needed for your PR before you take up an another issue. Once you finish that, I can assign this issue to you. @AmitGupta700

**Comment by Debashish-hub** [comment]
Why did you closed it @AmitGupta700

**Comment by prathimacode-hub** [comment]
@AmitGupta700. Yes, you had submitted the PR. Its' merged as well yesterday. But you raised this issue, when you was working on other PR. So I said you finish that PR, before you work on this. You hadn't checked up this issue since past 2 days. As it's on FCFS even though you raised the issue as you haven't responded back here yet, I did say her to raise an issue separately if you want to work on. Kindly check the time period as well. By the time you check it, lots of things might have happened in this repo. Also one more thing, you should never close issue or PR from your end. Hope this clarified you. Issues always will be assigned on FCFS basis.

**Comment by AmitGupta700** [comment]
Sorry, Mam By mistake it was closed I m really very sorry.

**Comment by prathimacode-hub** [comment]
That's fine. Issue is assigned to you. No worries. @AmitGupta700

**Comment by Debashish-hub** [comment]
Hey @AmitGupta700 Is everything going good, No updates since 5 days
