### ISSUE TITLE
A face Lock Application using OpenCV

### ISSUE THREAD

**Issue by shantamsultania** [prathimacode-hub/Awesome_Python_Scripts#254]
I want to mimic the face lock system used by the Mobile using Python and openCV

**Comment by prathimacode-hub** [comment]
You can work on only 1 issue at a time, And to get issue assigned to you, you need to follow the issue template given in README file of the project. @shantamsultania

**Comment by ainy-123** [comment]
> You can work on only 1 issue at a time, And to get issue assigned to you, you need to follow the issue template given in README file of the project. @shantamsultania

I want to work on this issue as an LGM-SoC'21 participant. Will you please assign this to me?

**Comment by prathimacode-hub** [comment]
You can work on this, once you finish earlier assigned issue. @ainy-123

**Comment by dilroseR** [comment]
Can i take up this?

**Comment by prathimacode-hub** [comment]
Yes, you take up. But before that correct the changes requested in your earlier PR. Then I shall assign this to you. @dilroseR

**Comment by TusharAMD** [comment]
If its up for grab can I do this one?

**Comment by prathimacode-hub** [comment]
Yes, you can. Do you want to work on it? Then add up an issue template along with your details and changes with respect to your accordingly to get it assigned to you. @TusharAMD

**Comment by dilroseR** [comment]
> Can i take up this?

@prathimacode-hub ? Who are you assigning this to? :}

**Comment by prathimacode-hub** [comment]
See, issues are on FCFS. If you are not here, I have to assign it to someone who is here. I haven't assigned it to anyone else. If you want to work on it, then add up an issue template along with your details and changes with respect to your accordingly to get it assigned to you. @dilroseR

**Comment by TusharAMD** [comment]
---
Title: A face Lock Application using OpenCV
About: Lock Screen which can be unlocked using face detection in OpenCV
Name: Tushar Amdoskar
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor




**Is your feature request related to a problem? Please describe.**

Yes. This is about awesome python scripts



**Describe the solution you'd like...**
The topic is A face Lock Application using OpenCV
As we know in windows there is no default face lock mechanism present for most of the computers (Windows hello is not available on all PCs). That's why this project can be a good way to make our own lock screen that can be opened by face lock. So we need to use open cv face detection to recognise faces and on correct face we should unlock the screen.I think at this stage the program can be made with minimal GUI. At first user will run a script to lock the screen. After doing so the user can no longer access the keyboard or mouse and will have to show his/her face to unlock. 



**Describe alternatives you've considered?**

At first I thought of using windows lock shorcut key and bind it in python program to lock the screen. But I found out that once system is locked there is no way to re run the face detection and unlock the screen. Thats why I decided to went for another approch which is mentioned below.



**Approach to be followed (optional):**

This is approch I am following to make a lock screen. 
1. First make a tkinter window of fullscreen size which will make sure nothing can be seen (not even menu bar) and it will only show the tkinter window
2. Then set a opencv live stream of small size (manually reduce size as some webcam images can be big) and put it over tkinter frame.
3. As soon as lock screen is active disable keyboard and mouse operations completely making sure that user can't terminate the program <- Achieved till this point till now
4. Detect the face and once it is detected close the lock screen and re enable all input devices.
5. Optionally put lock screen videos or gifs or slides at background



**Additional context**

This is the link where I have uploaded image of what I have made till now. https://i.ibb.co/Gn7yb7h/Image-960.png. This image is full screen snapshot and we can see how the lock screen covers everything. It also locks mouse and keyboard but I couldn't demonstrate
Please note that the click and quit button will be removed in final stage.

**Comment by prathimacode-hub** [comment]
Issue assigned. @TusharAMD

**Comment by prathimacode-hub** [comment]
> > Can i take up this?
> 
> @prathimacode-hub ? Who are you assigning this to? :}

Sorry, you are late. As other participant has added up the issue template first, I had to assign this issue to him. No worries you can come up with new issues. Sky is the limit. Don't get disheartned. @dilroseR

**Comment by dilroseR** [comment]
> See, issues are on FCFS. If you are not here, I have to assign it to someone who is here. I haven't assigned it to anyone else. If you want to work on it, then add up an issue template along with your details and changes with respect to your accordingly to get it assigned to you. @dilroseR

I just said that because you told after correcting my PR changes you'll assign it to me, i didn't know that i had to come back and ask it again.
Its okay now, the issue template has been given

**Comment by prathimacode-hub** [comment]
> > See, issues are on FCFS. If you are not here, I have to assign it to someone who is here. I haven't assigned it to anyone else. If you want to work on it, then add up an issue template along with your details and changes with respect to your accordingly to get it assigned to you. @dilroseR
> 
> I just said that because you told after correcting my PR changes you'll assign it to me, i didn't know that i had to come back and ask it again.
> Its okay now, the issue template has been given

Yes, I did say. But you got few mins late due to which I had to assign it to other. I have to be fair with everyone right. @dilroseR

**Comment by dilroseR** [comment]
> > > See, issues are on FCFS. If you are not here, I have to assign it to someone who is here. I haven't assigned it to anyone else. If you want to work on it, then add up an issue template along with your details and changes with respect to your accordingly to get it assigned to you. @dilroseR
> > 
> > 
> > I just said that because you told after correcting my PR changes you'll assign it to me, i didn't know that i had to come back and ask it again.
> > Its okay now, the issue template has been given
> 
> Yes, I did say. But you got few mins late due to which I had to assign it to other. I have to be fair with everyone right. @dilroseR

No issues! 👍
