### ISSUE TITLE
pygames

### ISSUE THREAD

**Issue by pragyakhanna11** [prathimacode-hub/Awesome_Python_Scripts#29]
To contribute codes for pygames, such as snake game and pong

**Comment by prathimacode-hub** [comment]
That's great to hear. I have assigned it to you. Sure, follow the contributing guidelines and go ahead. You can add your script in this [repository](https://github.com/prathimacode-hub/Awesome_Python_Scripts/tree/main/PyGamesScripts). And one more thing, be specific about the program you're going to contribute be it any pygame, so that it's easier for others to know as well. Good to see your initiation. 👍@pragyakhanna11
