### ISSUE TITLE
Adding alien invaders

### ISSUE THREAD

**Issue by Jordistyd** [prathimacode-hub/Awesome_Python_Scripts#291]
Title: Alien invaders Game
About: The game is about the player taking control of a ship to destroy incoming alien invaders.
once all invaders are destroyed the level advances and becomes gradually harder.
I built the game using pygame and images found on google
I would love to contribute the game to you open source project
Name: Yarden Galon
Label: Feature Request
Assignee: ''

**Comment by prathimacode-hub** [comment]
Are you a LGMSOC participant?
@Jordistyd

**Comment by Jordistyd** [comment]
Well, no
Sorry if I seem out of place but could you elaborate on what that is?

**Comment by prathimacode-hub** [comment]
No, that's Ok. LGMSOC is a open source program. This repo is part of it. Still, it's open for all contributors whether they are participants or not. It doesn't matter. I just asked to know, so that I can move things forward according to that. Sure, you can start working on this issue. It's assigned to you. @Jordistyd

**Comment by Jordistyd** [comment]
Great to hear it!
thank you and I'll get to work
