### ISSUE TITLE
guessing a number game using python

### ISSUE THREAD

**Issue by manognyaa** [prathimacode-hub/Awesome_Python_Scripts#41]
hello sir,
i would like to add guessing number using python . _please assign this to me_

**Comment by prathimacode-hub** [comment]
Good initation. Welcome to the repository. Assigning it to you. 🙂@manognyaa

**Comment by manognyaa** [comment]
> Good initation. Welcome to the repository. Assigning it to you. @manognyaa

Thank You mam. It really means a lot :) @prathimacode-hub

**Comment by neelshah2409** [comment]
Mam even I wanted to contribute to these so you can also assign me please...

**Comment by prathimacode-hub** [comment]
Are you LGM-SOC participant? Always to communicate you should raise a new issue. If you are a open source contributor, you should first create a new issue with the project title and details about the project you are going to contribute. Also make sure you read the project README and CONTRIBUTING GUIDELINES. So that you know how to proceed it further. If you're a LGM-SOC participant, I can only assign it after june 10th. @neelshah2409
